name: CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    services:
      db:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@main
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.13
      - name: Install Dependencies
        run: mix deps.get
      - name: Compile Dependencies
        run: mix deps.compile
      - name: Create test Database
        run: mix ecto.create
      - name: Run Tests
        run: mix test
  
  build-docker-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mcstats:latest